package it.prisma.dal.entities.paas.services.mqaas;

// Generated 17-set-2014 21.25.53 by Hibernate Tools 3.4.0.CR1

import it.prisma.dal.entities.paas.services.AbstractPaaSService;
import it.prisma.dal.entities.paas.services.PaaSService;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * MQaaS generated by hbm2java
 */
@Entity
@Table(name = "MQaaS")
public class MQaaS extends AbstractPaaSService implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2687848234597969271L;
	private long queueaaSid;
	private String productType;
	private String productVersion;

	public MQaaS() {
	}

	public MQaaS(PaaSService paaSservice, String productType,
			String productVersion) {
		this.paaSService = paaSservice;
		this.productType = productType;
		this.productVersion = productVersion;

	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "paaSService"))
	@Id
	@GeneratedValue(generator = "generator")
	// @Id
	// @GeneratedValue(strategy = IDENTITY)
	@Column(name = "QueueaaSID", unique = true, nullable = false)
	public long getId() {
		return this.queueaaSid;
	}

	public void setId(long queueaaSid) {
		this.queueaaSid = queueaaSid;
	}

	@OneToOne(fetch = FetchType.EAGER)
	@PrimaryKeyJoinColumn
	public PaaSService getPaaSService() {
		return this.paaSService;
	}

	public void setPaaSService(PaaSService paaSservice) {
		this.paaSService = paaSservice;
	}

	@Column(name = "productType", nullable = false, length = 128)
	public String getProductType() {
		return this.productType;
	}

	public void setProductType(String productType) {
		this.productType = productType;
	}

	@Column(name = "productVersion", nullable = false, length = 128)
	public String getProductVersion() {
		return this.productVersion;
	}

	public void setProductVersion(String productVersion) {
		this.productVersion = productVersion;
	}

}
