package it.prisma.dal.entities.paas.services.mqaas;
//package it.prisma.dal.entities.paas.services.mqaas;
//
//// Generated 17-set-2014 21.25.53 by Hibernate Tools 3.4.0.CR1
//
//import java.util.Date;
//import javax.persistence.Column;
//import javax.persistence.Embeddable;
//
///**
// * QueueaaSdetailsId generated by hbm2java
// */
//@Embeddable
//public class QueueaaSDetailsId implements java.io.Serializable {
//
//	/**
//	 * 
//	 */
//	private static final long serialVersionUID = 5270734353100768739L;
//	private long queueaaSid;
//	private String productType;
//	private String productName;
//	private int loadBalancingInstances;
//	private String domainName;
//	private boolean secureConnectionEnabled;
//	private String certificatePath;
//	private String iaaSflavor;
//	private String securityGroup;
//	private String notificationEmail;
//	private long paaSserviceId;
//	private long workgroupId;
//	private long userAccountId;
//	private Long paaSdeploymentId;
//	private String type;
//	private String name;
//	private String description;
//	private String status;
//	private String operation;
//	private String errorDescription;
//	private Date cretedAt;
//
//	public QueueaaSDetailsId() {
//	}
//
//	public QueueaaSDetailsId(long queueaaSid, String productType,
//			String productName, int loadBalancingInstances, String domainName,
//			boolean secureConnectionEnabled, String iaaSflavor,
//			String securityGroup, String notificationEmail, long paaSserviceId,
//			long workgroupId, long userAccountId, String type, String name,
//			String description, Date cretedAt) {
//		this.queueaaSid = queueaaSid;
//		this.productType = productType;
//		this.productName = productName;
//		this.loadBalancingInstances = loadBalancingInstances;
//		this.domainName = domainName;
//		this.secureConnectionEnabled = secureConnectionEnabled;
//		this.iaaSflavor = iaaSflavor;
//		this.securityGroup = securityGroup;
//		this.notificationEmail = notificationEmail;
//		this.paaSserviceId = paaSserviceId;
//		this.workgroupId = workgroupId;
//		this.userAccountId = userAccountId;
//		this.type = type;
//		this.name = name;
//		this.description = description;
//		this.cretedAt = cretedAt;
//	}
//
//	public QueueaaSDetailsId(long queueaaSid, String productType,
//			String productName, int loadBalancingInstances, String domainName,
//			boolean secureConnectionEnabled, String certificatePath,
//			String iaaSflavor, String securityGroup, String notificationEmail,
//			long paaSserviceId, long workgroupId, long userAccountId,
//			Long paaSdeploymentId, String type, String name,
//			String description, String status, String operation,
//			String errorDescription, Date cretedAt) {
//		this.queueaaSid = queueaaSid;
//		this.productType = productType;
//		this.productName = productName;
//		this.loadBalancingInstances = loadBalancingInstances;
//		this.domainName = domainName;
//		this.secureConnectionEnabled = secureConnectionEnabled;
//		this.certificatePath = certificatePath;
//		this.iaaSflavor = iaaSflavor;
//		this.securityGroup = securityGroup;
//		this.notificationEmail = notificationEmail;
//		this.paaSserviceId = paaSserviceId;
//		this.workgroupId = workgroupId;
//		this.userAccountId = userAccountId;
//		this.paaSdeploymentId = paaSdeploymentId;
//		this.type = type;
//		this.name = name;
//		this.description = description;
//		this.status = status;
//		this.operation = operation;
//		this.errorDescription = errorDescription;
//		this.cretedAt = cretedAt;
//	}
//
//	@Column(name = "QueueaaSID", nullable = false)
//	public long getQueueaaSid() {
//		return this.queueaaSid;
//	}
//
//	public void setQueueaaSid(long queueaaSid) {
//		this.queueaaSid = queueaaSid;
//	}
//
//	@Column(name = "productType", nullable = false, length = 45)
//	public String getProductType() {
//		return this.productType;
//	}
//
//	public void setProductType(String productType) {
//		this.productType = productType;
//	}
//
//	@Column(name = "productName", nullable = false, length = 45)
//	public String getProductName() {
//		return this.productName;
//	}
//
//	public void setProductName(String productName) {
//		this.productName = productName;
//	}
//
//	@Column(name = "loadBalancingInstances", nullable = false)
//	public int getLoadBalancingInstances() {
//		return this.loadBalancingInstances;
//	}
//
//	public void setLoadBalancingInstances(int loadBalancingInstances) {
//		this.loadBalancingInstances = loadBalancingInstances;
//	}
//
//	@Column(name = "domainName", nullable = false, length = 256)
//	public String getDomainName() {
//		return this.domainName;
//	}
//
//	public void setDomainName(String domainName) {
//		this.domainName = domainName;
//	}
//
//	@Column(name = "secureConnectionEnabled", columnDefinition = "bit", nullable = false)
//	public boolean isSecureConnectionEnabled() {
//		return this.secureConnectionEnabled;
//	}
//
//	public void setSecureConnectionEnabled(boolean secureConnectionEnabled) {
//		this.secureConnectionEnabled = secureConnectionEnabled;
//	}
//
//	@Column(name = "certificatePath", length = 45)
//	public String getCertificatePath() {
//		return this.certificatePath;
//	}
//
//	public void setCertificatePath(String certificatePath) {
//		this.certificatePath = certificatePath;
//	}
//
//	@Column(name = "IaaSFlavor", nullable = false, length = 256)
//	public String getIaaSflavor() {
//		return this.iaaSflavor;
//	}
//
//	public void setIaaSflavor(String iaaSflavor) {
//		this.iaaSflavor = iaaSflavor;
//	}
//
//	@Column(name = "securityGroup", nullable = false, length = 45)
//	public String getSecurityGroup() {
//		return this.securityGroup;
//	}
//
//	public void setSecurityGroup(String securityGroup) {
//		this.securityGroup = securityGroup;
//	}
//
//	@Column(name = "notificationEmail", nullable = false, length = 256)
//	public String getNotificationEmail() {
//		return this.notificationEmail;
//	}
//
//	public void setNotificationEmail(String notificationEmail) {
//		this.notificationEmail = notificationEmail;
//	}
//
//	@Column(name = "PaaSServiceID", nullable = false)
//	public long getPaaSServiceId() {
//		return this.paaSserviceId;
//	}
//
//	public void setPaaSServiceId(long paaSserviceId) {
//		this.paaSserviceId = paaSserviceId;
//	}
//
//	@Column(name = "workgroupID", nullable = false)
//	public long getWorkgroupId() {
//		return this.workgroupId;
//	}
//
//	public void setWorkgroupId(long workgroupId) {
//		this.workgroupId = workgroupId;
//	}
//
//	@Column(name = "userAccountID", nullable = false)
//	public long getUserAccountId() {
//		return this.userAccountId;
//	}
//
//	public void setUserAccountId(long userAccountId) {
//		this.userAccountId = userAccountId;
//	}
//
//	@Column(name = "PaaSDeploymentID")
//	public Long getPaaSdeploymentId() {
//		return this.paaSdeploymentId;
//	}
//
//	public void setPaaSdeploymentId(Long paaSdeploymentId) {
//		this.paaSdeploymentId = paaSdeploymentId;
//	}
//
//	@Column(name = "type", nullable = false, length = 8)
//	public String getType() {
//		return this.type;
//	}
//
//	public void setType(String type) {
//		this.type = type;
//	}
//
//	@Column(name = "name", nullable = false, length = 128)
//	public String getName() {
//		return this.name;
//	}
//
//	public void setName(String name) {
//		this.name = name;
//	}
//
//	@Column(name = "description", nullable = false, length = 2048)
//	public String getDescription() {
//		return this.description;
//	}
//
//	public void setDescription(String description) {
//		this.description = description;
//	}
//
//	@Column(name = "status", length = 8)
//	public String getStatus() {
//		return this.status;
//	}
//
//	public void setStatus(String status) {
//		this.status = status;
//	}
//
//	@Column(name = "operation", length = 45)
//	public String getOperation() {
//		return this.operation;
//	}
//
//	public void setOperation(String operation) {
//		this.operation = operation;
//	}
//
//	@Column(name = "errorDescription", length = 45)
//	public String getErrorDescription() {
//		return this.errorDescription;
//	}
//
//	public void setErrorDescription(String errorDescription) {
//		this.errorDescription = errorDescription;
//	}
//
//	@Column(name = "cretedAt", nullable = false, length = 19)
//	public Date getCretedAt() {
//		return this.cretedAt;
//	}
//
//	public void setCretedAt(Date cretedAt) {
//		this.cretedAt = cretedAt;
//	}
//
//	public boolean equals(Object other) {
//		if ((this == other))
//			return true;
//		if ((other == null))
//			return false;
//		if (!(other instanceof QueueaaSDetailsId))
//			return false;
//		QueueaaSDetailsId castOther = (QueueaaSDetailsId) other;
//
//		return (this.getQueueaaSid() == castOther.getQueueaaSid())
//				&& ((this.getProductType() == castOther.getProductType()) || (this
//						.getProductType() != null
//						&& castOther.getProductType() != null && this
//						.getProductType().equals(castOther.getProductType())))
//				&& ((this.getProductName() == castOther.getProductName()) || (this
//						.getProductName() != null
//						&& castOther.getProductName() != null && this
//						.getProductName().equals(castOther.getProductName())))
//				&& (this.getLoadBalancingInstances() == castOther
//						.getLoadBalancingInstances())
//				&& ((this.getDomainName() == castOther.getDomainName()) || (this
//						.getDomainName() != null
//						&& castOther.getDomainName() != null && this
//						.getDomainName().equals(castOther.getDomainName())))
//				&& (this.isSecureConnectionEnabled() == castOther
//						.isSecureConnectionEnabled())
//				&& ((this.getCertificatePath() == castOther
//						.getCertificatePath()) || (this.getCertificatePath() != null
//						&& castOther.getCertificatePath() != null && this
//						.getCertificatePath().equals(
//								castOther.getCertificatePath())))
//				&& ((this.getIaaSflavor() == castOther.getIaaSflavor()) || (this
//						.getIaaSflavor() != null
//						&& castOther.getIaaSflavor() != null && this
//						.getIaaSflavor().equals(castOther.getIaaSflavor())))
//				&& ((this.getSecurityGroup() == castOther.getSecurityGroup()) || (this
//						.getSecurityGroup() != null
//						&& castOther.getSecurityGroup() != null && this
//						.getSecurityGroup()
//						.equals(castOther.getSecurityGroup())))
//				&& ((this.getNotificationEmail() == castOther
//						.getNotificationEmail()) || (this
//						.getNotificationEmail() != null
//						&& castOther.getNotificationEmail() != null && this
//						.getNotificationEmail().equals(
//								castOther.getNotificationEmail())))
//				&& (this.getPaaSServiceId() == castOther.getPaaSServiceId())
//				&& (this.getWorkgroupId() == castOther.getWorkgroupId())
//				&& (this.getUserAccountId() == castOther.getUserAccountId())
//				&& ((this.getPaaSdeploymentId() == castOther
//						.getPaaSdeploymentId()) || (this.getPaaSdeploymentId() != null
//						&& castOther.getPaaSdeploymentId() != null && this
//						.getPaaSdeploymentId().equals(
//								castOther.getPaaSdeploymentId())))
//				&& ((this.getType() == castOther.getType()) || (this.getType() != null
//						&& castOther.getType() != null && this.getType()
//						.equals(castOther.getType())))
//				&& ((this.getName() == castOther.getName()) || (this.getName() != null
//						&& castOther.getName() != null && this.getName()
//						.equals(castOther.getName())))
//				&& ((this.getDescription() == castOther.getDescription()) || (this
//						.getDescription() != null
//						&& castOther.getDescription() != null && this
//						.getDescription().equals(castOther.getDescription())))
//				&& ((this.getStatus() == castOther.getStatus()) || (this
//						.getStatus() != null && castOther.getStatus() != null && this
//						.getStatus().equals(castOther.getStatus())))
//				&& ((this.getOperation() == castOther.getOperation()) || (this
//						.getOperation() != null
//						&& castOther.getOperation() != null && this
//						.getOperation().equals(castOther.getOperation())))
//				&& ((this.getErrorDescription() == castOther
//						.getErrorDescription()) || (this.getErrorDescription() != null
//						&& castOther.getErrorDescription() != null && this
//						.getErrorDescription().equals(
//								castOther.getErrorDescription())))
//				&& ((this.getCretedAt() == castOther.getCretedAt()) || (this
//						.getCretedAt() != null
//						&& castOther.getCretedAt() != null && this
//						.getCretedAt().equals(castOther.getCretedAt())));
//	}
//
//	public int hashCode() {
//		int result = 17;
//
//		result = 37 * result + (int) this.getQueueaaSid();
//		result = 37
//				* result
//				+ (getProductType() == null ? 0 : this.getProductType()
//						.hashCode());
//		result = 37
//				* result
//				+ (getProductName() == null ? 0 : this.getProductName()
//						.hashCode());
//		result = 37 * result + this.getLoadBalancingInstances();
//		result = 37
//				* result
//				+ (getDomainName() == null ? 0 : this.getDomainName()
//						.hashCode());
//		result = 37 * result + (this.isSecureConnectionEnabled() ? 1 : 0);
//		result = 37
//				* result
//				+ (getCertificatePath() == null ? 0 : this.getCertificatePath()
//						.hashCode());
//		result = 37
//				* result
//				+ (getIaaSflavor() == null ? 0 : this.getIaaSflavor()
//						.hashCode());
//		result = 37
//				* result
//				+ (getSecurityGroup() == null ? 0 : this.getSecurityGroup()
//						.hashCode());
//		result = 37
//				* result
//				+ (getNotificationEmail() == null ? 0 : this
//						.getNotificationEmail().hashCode());
//		result = 37 * result + (int) this.getPaaSServiceId();
//		result = 37 * result + (int) this.getWorkgroupId();
//		result = 37 * result + (int) this.getUserAccountId();
//		result = 37
//				* result
//				+ (getPaaSdeploymentId() == null ? 0 : this
//						.getPaaSdeploymentId().hashCode());
//		result = 37 * result
//				+ (getType() == null ? 0 : this.getType().hashCode());
//		result = 37 * result
//				+ (getName() == null ? 0 : this.getName().hashCode());
//		result = 37
//				* result
//				+ (getDescription() == null ? 0 : this.getDescription()
//						.hashCode());
//		result = 37 * result
//				+ (getStatus() == null ? 0 : this.getStatus().hashCode());
//		result = 37 * result
//				+ (getOperation() == null ? 0 : this.getOperation().hashCode());
//		result = 37
//				* result
//				+ (getErrorDescription() == null ? 0 : this
//						.getErrorDescription().hashCode());
//		result = 37 * result
//				+ (getCretedAt() == null ? 0 : this.getCretedAt().hashCode());
//		return result;
//	}
//
//}
