package it.prisma.dal.entities.config;

//Generated Sep 8, 2014 12:47:13 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
* Configurations generated by hbm2java
*/
@Entity
//@Table(name = "configuration", catalog = "prisma_config")
@Table(name = "configuration")
public class PlatformConfiguration implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5118051185675529700L;
	private String key;
	private String value;

	public PlatformConfiguration() {
	}

	public PlatformConfiguration(String key) {
		this.key = key;
	}

	public PlatformConfiguration(String key, String value) {
		this.key = key;
		this.value = value;
	}

	@Id
	@Column(name = "key", unique = true, nullable = false)
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
