package it.prisma.dal.entities.paas.services;

// Generated 17-set-2014 21.25.53 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.Type;

/**
 * PaaSserviceEvent generated by hbm2java
 */
@Entity
@DynamicInsert
@DynamicUpdate
@Table(name = "PaaSServiceEvent")
public class PaaSServiceEvent implements java.io.Serializable {

	public enum EventType {
		INFO, ERROR, WARNING;
	}
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 8713893864702523404L;
	private Long eventId;
	private Date createdAt;
	private PaaSService paaSservice;
	private String type;
	private String details;
	private String verbose;

	public PaaSServiceEvent() {
	}

	public PaaSServiceEvent(PaaSService paaSservice, String type, String details) {
		this.paaSservice = paaSservice;
		this.type = type;
		this.details = details;
	}
	
	public PaaSServiceEvent(PaaSService paaSservice, String type, String details, String verbose) {
		this.paaSservice = paaSservice;
		this.type = type;
		this.details = details;
		this.verbose=verbose;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "EventID", unique = true, nullable = false)
	public Long getId() {
		return this.eventId;
	}

	public void setId(Long eventId) {
		this.eventId = eventId;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdAt", nullable = false, length = 19, insertable=false, updatable=false)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PaaSServiceID", nullable = false)
	public PaaSService getPaaSService() {
		return this.paaSservice;
	}

	public void setPaaSService(PaaSService paaSservice) {
		this.paaSservice = paaSservice;
	}

	@Column(name = "type", nullable = false, length = 32)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "details", nullable = false, length = 65535)
	@Type(type="text")
	public String getDetails() {
		return this.details;
	}

	public void setDetails(String details) {
		this.details = details;
	}
	
	@Column(name = "verbose", nullable = false, length = 65535)
	@Type(type="text")
	public String getVerbose() {
		return this.verbose;
	}

	public void setVerbose(String verbose) {
		this.verbose = verbose;
	}

}
