package it.prisma.dal.entities.paas.services.appaas;
// Generated 8-ott-2014 17.56.50 by Hibernate Tools 4.0.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * APPaaSEnvironmentDetailsViewId generated by hbm2java
 */
@Embeddable
public class APPaaSEnvironmentDetailsViewId  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 970668916386255297L;
	private long Id;
     private long Id_1;
     private String serverType;
     private long Id_2;

    public APPaaSEnvironmentDetailsViewId() {
    }

    public APPaaSEnvironmentDetailsViewId(long Id, long Id_1, String serverType, long Id_2) {
       this.Id = Id;
       this.Id_1 = Id_1;
       this.serverType = serverType;
       this.Id_2 = Id_2;
    }
   


    @Column(name="APPaaSEnvironmentID", nullable=false)
    public long getId() {
        return this.Id;
    }
    
    public void setId(long Id) {
        this.Id = Id;
    }


    @Column(name="APPaaSID", nullable=false)
    public long getId_1() {
        return this.Id_1;
    }
    
    public void setId_1(long Id_1) {
        this.Id_1 = Id_1;
    }


    @Column(name="serverType", nullable=false, length=64)
    public String getServerType() {
        return this.serverType;
    }
    
    public void setServerType(String serverType) {
        this.serverType = serverType;
    }


    @Column(name="currentAppFile_ApplicationRepositoryEntryID", nullable=false)
    public long getId_2() {
        return this.Id_2;
    }
    
    public void setId_2(long Id_2) {
        this.Id_2 = Id_2;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof APPaaSEnvironmentDetailsViewId) ) return false;
		 APPaaSEnvironmentDetailsViewId castOther = ( APPaaSEnvironmentDetailsViewId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getId_1()==castOther.getId_1())
 && ( (this.getServerType()==castOther.getServerType()) || ( this.getServerType()!=null && castOther.getServerType()!=null && this.getServerType().equals(castOther.getServerType()) ) )
 && (this.getId_2()==castOther.getId_2());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getId();
         result = 37 * result + (int) this.getId_1();
         result = 37 * result + ( getServerType() == null ? 0 : this.getServerType().hashCode() );
         result = 37 * result + (int) this.getId_2();
         return result;
   }   


}


