package it.prisma.dal.entities.paas.services.appaas;

// Generated 17-set-2014 21.25.53 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * AppaaSappFileHistory generated by hbm2java
 */
@Entity
@Table(name = "APPaaSAppFileHistory")
public class AppaaSAppFileHistory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6397292982820400108L;
	private Long appaaSappFileHistoryId;
	private Date createdAt;
	private ApplicationRepositoryEntry applicationRepositoryEntry;
	private AppaaSEnvironment appaaSenvironment;

	public AppaaSAppFileHistory() {
	}

	public AppaaSAppFileHistory(
			ApplicationRepositoryEntry applicationRepositoryEntry,
			AppaaSEnvironment appaaSenvironment) {
		this.applicationRepositoryEntry = applicationRepositoryEntry;
		this.appaaSenvironment = appaaSenvironment;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "APPaaSAppFileHistoryID", unique = true, nullable = false)
	public Long getId() {
		return this.appaaSappFileHistoryId;
	}

	public void setId(Long appaaSappFileHistoryId) {
		this.appaaSappFileHistoryId = appaaSappFileHistoryId;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdAt", nullable = false, length = 19, insertable=false, updatable=false)
	public Date getcreatedAt() {
		return this.createdAt;
	}

	public void setcreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "APPaaSAppFileID", nullable = false)
	public ApplicationRepositoryEntry getApplicationRepositoryEntry() {
		return this.applicationRepositoryEntry;
	}

	public void setApplicationRepositoryEntry(
			ApplicationRepositoryEntry applicationRepositoryEntry) {
		this.applicationRepositoryEntry = applicationRepositoryEntry;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "APPaaSEnvironmentID", nullable = false)
	public AppaaSEnvironment getAppaaSenvironment() {
		return this.appaaSenvironment;
	}

	public void setAppaaSenvironment(AppaaSEnvironment appaaSenvironment) {
		this.appaaSenvironment = appaaSenvironment;
	}

}
