//package it.prisma.dal.entities.paas.services.appaas;
//
//// Generated 17-set-2014 21.25.53 by Hibernate Tools 3.4.0.CR1
//
//import it.prisma.dal.entities.paas.services.PaaSService;
//
//import java.util.HashSet;
//import java.util.Set;
//
//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.FetchType;
//import javax.persistence.GeneratedValue;
//import javax.persistence.Id;
//import javax.persistence.OneToMany;
//import javax.persistence.OneToOne;
//import javax.persistence.PrimaryKeyJoinColumn;
//import javax.persistence.Table;
//
//import org.hibernate.annotations.GenericGenerator;
//import org.hibernate.annotations.Parameter;
//
///**
// * AppaaS generated by hbm2java
// */
//@Entity
//@Table(name = "APPaaS")
//public class AppaaS implements java.io.Serializable {
//
//	/**
//	 * 
//	 */
//	private static final long serialVersionUID = -6954865700171509108L;
//	private long appaaSid;
//	private PaaSService paaSservice;
//	private Set<AppaaSEnvironment> appaaSenvironments = new HashSet<AppaaSEnvironment>(0);
//
//	public AppaaS() {
//	}
//
//	public AppaaS(PaaSService paaSservice) {
//		this.paaSservice = paaSservice;
//	}
//
//	public AppaaS(PaaSService paaSservice, Set<AppaaSEnvironment> appaaSenvironments) {
//		this.paaSservice = paaSservice;
//		this.appaaSenvironments = appaaSenvironments;
//	}
//
//	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "paaSservice"))
//	@Id
//	@GeneratedValue(generator = "generator")
//	@Column(name = "APPaaSID", unique = true, nullable = false)
//	public long getId() {
//		return this.appaaSid;
//	}
//
//	public void setId(long appaaSid) {
//		this.appaaSid = appaaSid;
//	}
//
//	@OneToOne(fetch = FetchType.LAZY)
//	@PrimaryKeyJoinColumn
//	public PaaSService getPaaSService() {
//		return this.paaSservice;
//	}
//
//	public void setPaaSService(PaaSService paaSservice) {
//		this.paaSservice = paaSservice;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "appaaS")
//	public Set<AppaaSEnvironment> getAppaaSenvironments() {
//		return this.appaaSenvironments;
//	}
//
//	public void setAppaaSenvironments(Set<AppaaSEnvironment> appaaSenvironments) {
//		this.appaaSenvironments = appaaSenvironments;
//	}
//
//}
