//package it.prisma.dal.entities.paas.services.appaas;
//
//// Generated 17-set-2014 21.25.53 by Hibernate Tools 3.4.0.CR1
//
//import it.prisma.dal.entities.accounting.UserAccount;
//import it.prisma.dal.entities.accounting.Workgroup;
//import it.prisma.dal.entities.paas.deployments.PaaSDeployment;
//
//import java.util.Date;
//
//import javax.persistence.Entity;
//import javax.persistence.FetchType;
//import javax.persistence.GeneratedValue;
//import javax.persistence.Id;
//import javax.persistence.JoinColumn;
//import javax.persistence.ManyToOne;
//import javax.persistence.OneToOne;
//import javax.persistence.Table;
//
///**
// * AppaaSdetails generated by hbm2java
// */
//@Entity
//@Table(name = "APPaaSDetails")
//public class AppaaSDetails implements java.io.Serializable {
//
//	/**
//	 * 
//	 */
//	private static final long serialVersionUID = 8416544293465732014L;
//	
//	@Id
//	@GeneratedValue 
////	@OneToOne(fetch = FetchType.LAZY)
////	@PrimaryKeyJoinColumn
//	private Long paaSserviceId;
//	
//	@OneToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "APPaaSID", nullable = false)
//	private AppaaS appaaS;
//	
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "userAccountID", nullable = false)
//	private UserAccount userAccount;
//	
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "PaaSDeploymentID")
//	private PaaSDeployment paaSdeployment;
//	
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "workgroupID", nullable = false)
//	private Workgroup workgroup;
//	
//	private String type;
//	private String name;
//	private String description;
//	private String status;
//	private String operation;
//	private String errorDescription;
//	private Date createdAt;	
//	
//	public AppaaSDetails() {
//	}
//
//	public Long getPaaSServiceId() {
//		return paaSserviceId;
//	}
//
//
//	public AppaaS getAppaaS() {
//		return appaaS;
//	}
//
//
//	public UserAccount getUserAccount() {
//		return userAccount;
//	}
//
//
//	public PaaSDeployment getPaaSdeployment() {
//		return paaSdeployment;
//	}
//
//
//	public Workgroup getWorkgroup() {
//		return workgroup;
//	}
//
//
//	public String getType() {
//		return type;
//	}
//
//
//	public String getName() {
//		return name;
//	}
//
//
//	public String getDescription() {
//		return description;
//	}
//
//
//	public String getStatus() {
//		return status;
//	}
//
//
//	public String getOperation() {
//		return operation;
//	}
//
//
//	public String getErrorDescription() {
//		return errorDescription;
//	}
//
//
//	public Date getCreatedAt() {
//		return createdAt;
//	}
//
//}
