package it.prisma.dal.entities.paas.services.appaas;

// Generated 17-set-2014 21.25.53 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;
import it.prisma.dal.entities.accounting.UserAccount;
import it.prisma.dal.entities.accounting.Workgroup;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * ApplicationRepositoryEntry generated by hbm2java
 */
@Entity
@Table(name = "ApplicationRepositoryEntry", uniqueConstraints = @UniqueConstraint(columnNames = {
		"WorkgroupID", "UserAccountID", "applicationName", "tag" }))
public class ApplicationRepositoryEntry implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7897553971807748555L;
	private Long applicationRepositoryEntryId;
	private UserAccount userAccount;
	private Workgroup workgroup;
	private String applicationName;
	private String tag;
	private String description;
	private boolean shared;
	private String fileName;
	private String filePath;
	private Date createdAt;
	/**
	 * In bytes.
	 */
	private Long fileSize;
	private Set<AppaaSAppFileHistory> appaaSappFileHistories = new HashSet<AppaaSAppFileHistory>(
			0);
	private Set<AppaaSEnvironment> appaaSenvironments = new HashSet<AppaaSEnvironment>(
			0);

	public ApplicationRepositoryEntry() {
	}

	public ApplicationRepositoryEntry(UserAccount userAccount,
			Workgroup workgroup, String applicationName, String tag,
			String description, boolean shared, String fileName,
			String filePath, Long fileSize, Date createdAt) {
		this.userAccount = userAccount;
		this.workgroup = workgroup;
		this.applicationName = applicationName;
		this.tag = tag;
		this.description = description;
		this.shared = shared;
		this.fileName = fileName;
		this.filePath = filePath;
		this.createdAt = createdAt;
		this.fileSize = fileSize;
	}

	public ApplicationRepositoryEntry(UserAccount userAccount,
			Workgroup workgroup, String applicationName, String tag,
			String description, boolean shared, String fileName,
			String filePath, Long fileSize, Date createdAt,
			Set<AppaaSAppFileHistory> appaaSappFileHistories,
			Set<AppaaSEnvironment> appaaSenvironments) {
		this.userAccount = userAccount;
		this.workgroup = workgroup;
		this.applicationName = applicationName;
		this.tag = tag;
		this.description = description;
		this.shared = shared;
		this.fileName = fileName;
		this.filePath = filePath;
		this.createdAt = createdAt;
		this.appaaSappFileHistories = appaaSappFileHistories;
		this.appaaSenvironments = appaaSenvironments;
		this.fileSize = fileSize;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ApplicationRepositoryEntryID", unique = true, nullable = false)
	public Long getId() {
		return this.applicationRepositoryEntryId;
	}

	public void setId(Long applicationRepositoryEntryId) {
		this.applicationRepositoryEntryId = applicationRepositoryEntryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserAccountID", nullable = false)
	@JsonBackReference
	public UserAccount getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(UserAccount userAccount) {
		this.userAccount = userAccount;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "WorkgroupID", nullable = false)
	@JsonBackReference
	public Workgroup getWorkgroup() {
		return this.workgroup;
	}

	public void setWorkgroup(Workgroup workgroup) {
		this.workgroup = workgroup;
	}

	@Column(name = "applicationName", nullable = false, length = 45)
	public String getApplicationName() {
		return this.applicationName;
	}

	public void setApplicationName(String applicationName) {
		this.applicationName = applicationName;
	}

	@Column(name = "tag", nullable = false, length = 45)
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	@Column(name = "description", nullable = false, length = 2048)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "shared", columnDefinition = "bit", nullable = false)
	public boolean isShared() {
		return this.shared;
	}

	public void setShared(boolean shared) {
		this.shared = shared;
	}

	@Column(name = "fileName", nullable = false, length = 256)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "filePath", nullable = false, length = 1024)
	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	@Column(name = "fileSize", columnDefinition = "int", nullable = false)
	public Long getFileSize() {
		return fileSize;
	}

	public void setFileSize(Long fileSize) {
		this.fileSize = fileSize;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdAt", nullable = false, length = 19, insertable = false, updatable = false)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "applicationRepositoryEntry")
	@JsonBackReference
	public Set<AppaaSAppFileHistory> getAppaaSappFileHistories() {
		return this.appaaSappFileHistories;
	}

	public void setAppaaSappFileHistories(
			Set<AppaaSAppFileHistory> appaaSappFileHistories) {
		this.appaaSappFileHistories = appaaSappFileHistories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "applicationRepositoryEntry")
	@JsonBackReference
	public Set<AppaaSEnvironment> getAppaaSenvironments() {
		return this.appaaSenvironments;
	}

	public void setAppaaSenvironments(Set<AppaaSEnvironment> appaaSenvironments) {
		this.appaaSenvironments = appaaSenvironments;
	}

}
