//package it.prisma.dal.entities.paas.services.appaas;
//
//// Generated 17-set-2014 21.25.53 by Hibernate Tools 3.4.0.CR1
//
//import javax.persistence.AttributeOverride;
//import javax.persistence.AttributeOverrides;
//import javax.persistence.Column;
//import javax.persistence.EmbeddedId;
//import javax.persistence.Entity;
//import javax.persistence.Table;
//
///**
// * AppaaSdetails generated by hbm2java
// */
//@Entity
//@Table(name = "APPaaSDetails")
//public class CopyOfAppaaSDetails implements java.io.Serializable {
//
//	/**
//	 * 
//	 */
//	private static final long serialVersionUID = 8416544293465732014L;
//	private AppaaSDetailsId id;
//
//	public CopyOfAppaaSDetails() {
//	}
//
//	public CopyOfAppaaSDetails(AppaaSDetailsId id) {
//		this.id = id;
//	}
//
//	@EmbeddedId
//	@AttributeOverrides({
//			@AttributeOverride(name = "appaaSid", column = @Column(name = "APPaaSID", nullable = false)),
//			@AttributeOverride(name = "paaSserviceId", column = @Column(name = "PaaSServiceID", nullable = false)),
//			@AttributeOverride(name = "workgroupId", column = @Column(name = "workgroupID", nullable = false)),
//			@AttributeOverride(name = "userAccountId", column = @Column(name = "userAccountID", nullable = false)),
//			@AttributeOverride(name = "paaSdeploymentId", column = @Column(name = "PaaSDeploymentID")),
//			@AttributeOverride(name = "type", column = @Column(name = "type", nullable = false, length = 8)),
//			@AttributeOverride(name = "name", column = @Column(name = "name", nullable = false, length = 128)),
//			@AttributeOverride(name = "description", column = @Column(name = "description", nullable = false, length = 2048)),
//			@AttributeOverride(name = "status", column = @Column(name = "status", length = 8)),
//			@AttributeOverride(name = "operation", column = @Column(name = "operation", length = 45)),
//			@AttributeOverride(name = "errorDescription", column = @Column(name = "errorDescription", length = 45)),
//			@AttributeOverride(name = "cretedAt", column = @Column(name = "cretedAt", nullable = false, length = 19)) })
//	public AppaaSDetailsId getId() {
//		return this.id;
//	}
//
//	public void setId(AppaaSDetailsId id) {
//		this.id = id;
//	}
//
//}
