//package it.prisma.dal.entities.paas.services.appaas;
//
//// Generated 17-set-2014 21.25.53 by Hibernate Tools 3.4.0.CR1
//
//import java.util.Date;
//import javax.persistence.Column;
//import javax.persistence.Embeddable;
//
///**
// * AppaaSdetailsId generated by hbm2java
// */
//@Embeddable
//public class CopyOfAppaaSDetailsId implements java.io.Serializable {
//
//	/**
//	 * 
//	 */
//	private static final long serialVersionUID = 5899447376845916805L;
//	private long appaaSid;
//	private long paaSserviceId;
//	private long workgroupId;
//	private long userAccountId;
//	private Long paaSdeploymentId;
//	private String type;
//	private String name;
//	private String description;
//	private String status;
//	private String operation;
//	private String errorDescription;
//	private Date cretedAt;
//
//	public CopyOfAppaaSDetailsId() {
//	}
//
//	public CopyOfAppaaSDetailsId(long appaaSid, long paaSserviceId, long workgroupId,
//			long userAccountId, String type, String name, String description,
//			Date cretedAt) {
//		this.appaaSid = appaaSid;
//		this.paaSserviceId = paaSserviceId;
//		this.workgroupId = workgroupId;
//		this.userAccountId = userAccountId;
//		this.type = type;
//		this.name = name;
//		this.description = description;
//		this.cretedAt = cretedAt;
//	}
//
//	public CopyOfAppaaSDetailsId(long appaaSid, long paaSserviceId, long workgroupId,
//			long userAccountId, Long paaSdeploymentId, String type,
//			String name, String description, String status, String operation,
//			String errorDescription, Date cretedAt) {
//		this.appaaSid = appaaSid;
//		this.paaSserviceId = paaSserviceId;
//		this.workgroupId = workgroupId;
//		this.userAccountId = userAccountId;
//		this.paaSdeploymentId = paaSdeploymentId;
//		this.type = type;
//		this.name = name;
//		this.description = description;
//		this.status = status;
//		this.operation = operation;
//		this.errorDescription = errorDescription;
//		this.cretedAt = cretedAt;
//	}
//
//	@Column(name = "APPaaSID", nullable = false)
//	public long getAppaaSid() {
//		return this.appaaSid;
//	}
//
//	public void setAppaaSid(long appaaSid) {
//		this.appaaSid = appaaSid;
//	}
//
//	@Column(name = "PaaSServiceID", nullable = false)
//	public long getPaaSServiceId() {
//		return this.paaSserviceId;
//	}
//
//	public void setPaaSServiceId(long paaSserviceId) {
//		this.paaSserviceId = paaSserviceId;
//	}
//
//	@Column(name = "workgroupID", nullable = false)
//	public long getWorkgroupId() {
//		return this.workgroupId;
//	}
//
//	public void setWorkgroupId(long workgroupId) {
//		this.workgroupId = workgroupId;
//	}
//
//	@Column(name = "userAccountID", nullable = false)
//	public long getUserAccountId() {
//		return this.userAccountId;
//	}
//
//	public void setUserAccountId(long userAccountId) {
//		this.userAccountId = userAccountId;
//	}
//
//	@Column(name = "PaaSDeploymentID")
//	public Long getPaaSdeploymentId() {
//		return this.paaSdeploymentId;
//	}
//
//	public void setPaaSdeploymentId(Long paaSdeploymentId) {
//		this.paaSdeploymentId = paaSdeploymentId;
//	}
//
//	@Column(name = "type", nullable = false, length = 8)
//	public String getType() {
//		return this.type;
//	}
//
//	public void setType(String type) {
//		this.type = type;
//	}
//
//	@Column(name = "name", nullable = false, length = 128)
//	public String getName() {
//		return this.name;
//	}
//
//	public void setName(String name) {
//		this.name = name;
//	}
//
//	@Column(name = "description", nullable = false, length = 2048)
//	public String getDescription() {
//		return this.description;
//	}
//
//	public void setDescription(String description) {
//		this.description = description;
//	}
//
//	@Column(name = "status", length = 8)
//	public String getStatus() {
//		return this.status;
//	}
//
//	public void setStatus(String status) {
//		this.status = status;
//	}
//
//	@Column(name = "operation", length = 45)
//	public String getOperation() {
//		return this.operation;
//	}
//
//	public void setOperation(String operation) {
//		this.operation = operation;
//	}
//
//	@Column(name = "errorDescription", length = 45)
//	public String getErrorDescription() {
//		return this.errorDescription;
//	}
//
//	public void setErrorDescription(String errorDescription) {
//		this.errorDescription = errorDescription;
//	}
//
//	@Column(name = "cretedAt", nullable = false, length = 19)
//	public Date getCretedAt() {
//		return this.cretedAt;
//	}
//
//	public void setCretedAt(Date cretedAt) {
//		this.cretedAt = cretedAt;
//	}
//
//	public boolean equals(Object other) {
//		if ((this == other))
//			return true;
//		if ((other == null))
//			return false;
//		if (!(other instanceof CopyOfAppaaSDetailsId))
//			return false;
//		CopyOfAppaaSDetailsId castOther = (CopyOfAppaaSDetailsId) other;
//
//		return (this.getAppaaSid() == castOther.getAppaaSid())
//				&& (this.getPaaSServiceId() == castOther.getPaaSServiceId())
//				&& (this.getWorkgroupId() == castOther.getWorkgroupId())
//				&& (this.getUserAccountId() == castOther.getUserAccountId())
//				&& ((this.getPaaSdeploymentId() == castOther
//						.getPaaSdeploymentId()) || (this.getPaaSdeploymentId() != null
//						&& castOther.getPaaSdeploymentId() != null && this
//						.getPaaSdeploymentId().equals(
//								castOther.getPaaSdeploymentId())))
//				&& ((this.getType() == castOther.getType()) || (this.getType() != null
//						&& castOther.getType() != null && this.getType()
//						.equals(castOther.getType())))
//				&& ((this.getName() == castOther.getName()) || (this.getName() != null
//						&& castOther.getName() != null && this.getName()
//						.equals(castOther.getName())))
//				&& ((this.getDescription() == castOther.getDescription()) || (this
//						.getDescription() != null
//						&& castOther.getDescription() != null && this
//						.getDescription().equals(castOther.getDescription())))
//				&& ((this.getStatus() == castOther.getStatus()) || (this
//						.getStatus() != null && castOther.getStatus() != null && this
//						.getStatus().equals(castOther.getStatus())))
//				&& ((this.getOperation() == castOther.getOperation()) || (this
//						.getOperation() != null
//						&& castOther.getOperation() != null && this
//						.getOperation().equals(castOther.getOperation())))
//				&& ((this.getErrorDescription() == castOther
//						.getErrorDescription()) || (this.getErrorDescription() != null
//						&& castOther.getErrorDescription() != null && this
//						.getErrorDescription().equals(
//								castOther.getErrorDescription())))
//				&& ((this.getCretedAt() == castOther.getCretedAt()) || (this
//						.getCretedAt() != null
//						&& castOther.getCretedAt() != null && this
//						.getCretedAt().equals(castOther.getCretedAt())));
//	}
//
//	public int hashCode() {
//		int result = 17;
//
//		result = 37 * result + (int) this.getAppaaSid();
//		result = 37 * result + (int) this.getPaaSServiceId();
//		result = 37 * result + (int) this.getWorkgroupId();
//		result = 37 * result + (int) this.getUserAccountId();
//		result = 37
//				* result
//				+ (getPaaSdeploymentId() == null ? 0 : this
//						.getPaaSdeploymentId().hashCode());
//		result = 37 * result
//				+ (getType() == null ? 0 : this.getType().hashCode());
//		result = 37 * result
//				+ (getName() == null ? 0 : this.getName().hashCode());
//		result = 37
//				* result
//				+ (getDescription() == null ? 0 : this.getDescription()
//						.hashCode());
//		result = 37 * result
//				+ (getStatus() == null ? 0 : this.getStatus().hashCode());
//		result = 37 * result
//				+ (getOperation() == null ? 0 : this.getOperation().hashCode());
//		result = 37
//				* result
//				+ (getErrorDescription() == null ? 0 : this
//						.getErrorDescription().hashCode());
//		result = 37 * result
//				+ (getCretedAt() == null ? 0 : this.getCretedAt().hashCode());
//		return result;
//	}
//
//}
