package it.prisma.dal.entities.iaas.services;

// Generated Nov 26, 2014 3:32:36 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;
import it.prisma.dal.entities.accounting.Workgroup;
import it.prisma.dal.entities.iaas.services.vm.VMaaS;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * IaaSNetwork generated by hbm2java
 */
@Entity
@Access(AccessType.PROPERTY)
@Table(name = "IaaSNetwork")
public class IaaSNetwork implements Serializable {

	private static final long serialVersionUID = -2167741662751682699L;

	private Long Id;
	private String name;
	private String status;
	private String routerExternal;
	private String tenantId;
	private String adminStateUp;
	private boolean shared;
	private String openstackId;

	private Set<IaaSSubnet> iaasSubnet;

	private transient Set<VMaaS> vmaas = new HashSet<VMaaS>(0);

	private Workgroup workgroup;

	public IaaSNetwork() {
	}
	
	@ManyToMany(mappedBy="iaaSNetworks")
	public Set<VMaaS> getVmaas() {
		return vmaas;
	}

	public void setVmaas(Set<VMaaS> vmaas) {
		this.vmaas = vmaas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IaasNetworkID", unique = true, nullable = false)
	public Long getId() {
		return this.Id;
	}

	public void setId(Long Id) {
		this.Id = Id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status")
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "routerExternal")
	public String getRouterExternal() {
		return routerExternal;
	}

	public void setRouterExternal(String routerExternal) {
		this.routerExternal = routerExternal;
	}

	@Column(name = "tenantId")
	public String getTenantId() {
		return tenantId;
	}

	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}

	@Column(name = "adminStateUp")
	public String getAdminStateUp() {
		return adminStateUp;
	}

	public void setAdminStateUp(String adminStateUp) {
		this.adminStateUp = adminStateUp;
	}

	@Column(name = "shared", columnDefinition = "bit")
	public Boolean isShared() {
		return shared;
	}

	public void setShared(boolean shared) {
		this.shared = shared;
	}

	@Column(name = "openstackId")
	public String getOpenstackId() {
		return openstackId;
	}

	public void setOpenstackId(String openstackId) {
		this.openstackId = openstackId;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "iaasNetwork")
	@JsonBackReference
	public Set<IaaSSubnet> getIaasSubnet() {
		return iaasSubnet;
	}

	public void setIaasSubnet(Set<IaaSSubnet> iaasSubnet) {
		this.iaasSubnet = iaasSubnet;
	}

	// @OneToMany(fetch = FetchType.EAGER, mappedBy = "IaasNetwork")
	// @JsonBackReference
	// public Set<VMaaSHasIaaSNetwork> getVMaaSHasIaaSNetwork() {
	// return this.vmaasHasIaasNetwork;
	// }
	//
	// public void setVMaaSHasIaaSNetwork(
	// Set<VMaaSHasIaaSNetwork> vmaasHasIaasNetwork) {
	// this. vmaasHasIaasNetwork = vmaasHasIaasNetwork;
	// }

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "workgroupID", nullable = false)
	public Workgroup getWorkgroup() {
		return workgroup;
	}

	public void setWorkgroup(Workgroup workgroup) {
		this.workgroup = workgroup;
	}
}
