package it.prisma.dal.entities.iaas.services;

// Generated Nov 26, 2014 3:32:36 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * IaaSNetwork generated by hbm2java
 */
@Entity
@Table(name = "IaaSSubnet")
public class IaaSSubnet implements java.io.Serializable {

	private static final long serialVersionUID = -2167741662751682699L;
	
	private Long Id;
	private String name;
	private boolean enableDHCP;
	private String gatewayIp;
	private String cidr;
	private String ipVersion;
	private String openstackId;
	
	private Set<DNSNameServer> DnsNameservers;
	private Set<AllocationPool> allocationPools;
	
	private IaaSNetwork iaasNetwork;
	
	public IaaSSubnet() {
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IaasSubnetID", unique = true, nullable = false)
	public Long getId() {
		return this.Id;
	}

	public void setId(Long Id) {
		this.Id = Id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@Column(name = "enableDHCP", columnDefinition = "bit")
	public boolean isEnableDHCP() {
		return enableDHCP;
	}

	public void setEnableDHCP(boolean enableDHCP) {
		this.enableDHCP = enableDHCP;
	}

	@Column(name = "gatewayIp")
	public String getGatewayIp() {
		return gatewayIp;
	}

	public void setGatewayIp(String gatewayIp) {
		this.gatewayIp = gatewayIp;
	}

	@Column(name = "cidr")
	public String getCidr() {
		return cidr;
	}


	public void setCidr(String cidr) {
		this.cidr = cidr;
	}

	@Column(name = "ipVersion")
	public String getIpVersion() {
		return ipVersion;
	}


	public void setIpVersion(String ipVersion) {
		this.ipVersion = ipVersion;
	}
	
	@Column(name = "openstackId")
	public String getOpenstackId() {
		return openstackId;
	}


	public void setOpenstackId(String openstackId) {
		this.openstackId = openstackId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "iaasSubnet")
	@JsonBackReference
	public Set<DNSNameServer> getDnsNameservers() {
		return DnsNameservers;
	}

	public void setDnsNameservers(Set<DNSNameServer> dnsNameservers) {
		DnsNameservers = dnsNameservers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "iaasSubnet")
	@JsonBackReference
	public Set<AllocationPool> getAllocationPools() {
		return allocationPools;
	}

	public void setAllocationPools(Set<AllocationPool> allocationPools) {
		this.allocationPools = allocationPools;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IaasNetworkID", nullable = false)
	public IaaSNetwork getIaasNetwork() {
		return iaasNetwork;
	}


	public void setIaasNetwork(IaaSNetwork iaasNetwork) {
		this.iaasNetwork = iaasNetwork;
	}

}
