package it.prisma.dal.entities.iaas.services;

// Generated Nov 26, 2014 3:32:36 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * IaaSSecurityGroupRule generated by hbm2java
 */
@Entity
@Table(name = "IaaSSecurityGroupRule")
public class IaaSSecurityGroupRule implements java.io.Serializable {

	private static final long serialVersionUID = 2317198190313751922L;
	
	private Long Id;
	private IaaSSecurityGroup iaaSSecurityGroup;
	private String name;
	private String direction;
	private Integer portStart;
	private Integer portEnd;
	private String remote;
	private String protocol;
	private long Id_1;

	public IaaSSecurityGroupRule() {
	}

	public IaaSSecurityGroupRule(IaaSSecurityGroup iaaSSecurityGroup, long Id_1) {
		this.iaaSSecurityGroup = iaaSSecurityGroup;
		this.Id_1 = Id_1;
	}

	public IaaSSecurityGroupRule(IaaSSecurityGroup iaaSSecurityGroup,
			String name, String direction, Integer portStart, Integer portEnd,
			String remote, String protocol, long Id_1) {
		this.iaaSSecurityGroup = iaaSSecurityGroup;
		this.name = name;
		this.direction = direction;
		this.portStart = portStart;
		this.portEnd = portEnd;
		this.remote = remote;
		this.protocol = protocol;
		this.Id_1 = Id_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IaasSecurityGroupPortID", unique = true, nullable = false)
	public Long getId() {
		return this.Id;
	}

	public void setId(Long Id) {
		this.Id = Id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IaasSecurityGroupID", nullable = false)
	public IaaSSecurityGroup getIaaSSecurityGroup() {
		return this.iaaSSecurityGroup;
	}

	public void setIaaSSecurityGroup(IaaSSecurityGroup iaaSSecurityGroup) {
		this.iaaSSecurityGroup = iaaSSecurityGroup;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "direction", columnDefinition = "enum", length = 3)
	public String getDirection() {
		return this.direction;
	}

	public void setDirection(String direction) {
		this.direction = direction;
	}

	@Column(name = "portStart")
	public Integer getPortStart() {
		return this.portStart;
	}

	public void setPortStart(Integer portStart) {
		this.portStart = portStart;
	}

	@Column(name = "portEnd")
	public Integer getPortEnd() {
		return this.portEnd;
	}

	public void setPortEnd(Integer portEnd) {
		this.portEnd = portEnd;
	}

	@Column(name = "remote")
	public String getRemote() {
		return this.remote;
	}

	public void setRemote(String remote) {
		this.remote = remote;
	}

	@Column(name = "protocol")
	public String getProtocol() {
		return this.protocol;
	}

	public void setProtocol(String protocol) {
		this.protocol = protocol;
	}

	@Column(name = "securityGroup_securityGroupID", nullable = false)
	public long getId_1() {
		return this.Id_1;
	}

	public void setId_1(long Id_1) {
		this.Id_1 = Id_1;
	}

}
