package it.prisma.dal.entities.iaas.services;

// Generated Nov 26, 2014 3:32:36 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;
import it.prisma.dal.entities.iaas.services.vm.VMaaS;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * IaaSSecurityGroup generated by hbm2java
 */
@Entity
@Table(name = "IaaSSecurityGroup")
public class IaaSSecurityGroup implements java.io.Serializable {

	private static final long serialVersionUID = -8662438745772965173L;

	private Long Id;
	private VMaaS VMaaS;
	private String name;
	private Set<IaaSSecurityGroupRule> iaaSSecurityGroupRules = new HashSet<IaaSSecurityGroupRule>(
			0);

	public IaaSSecurityGroup() {
	}

	public IaaSSecurityGroup(VMaaS VMaaS) {
		this.VMaaS = VMaaS;
	}

	public IaaSSecurityGroup(VMaaS VMaaS, String name,
			Set<IaaSSecurityGroupRule> iaaSSecurityGroupRules) {
		this.VMaaS = VMaaS;
		this.name = name;
		this.iaaSSecurityGroupRules = iaaSSecurityGroupRules;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IaasSecurityGroupID", unique = true, nullable = false)
	public Long getId() {
		return this.Id;
	}

	public void setId(Long Id) {
		this.Id = Id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VMaaSID", nullable = false)
	public VMaaS getVMaaS() {
		return this.VMaaS;
	}

	public void setVMaaS(VMaaS VMaaS) {
		this.VMaaS = VMaaS;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "iaaSSecurityGroup")
	public Set<IaaSSecurityGroupRule> getIaaSSecurityGroupRules() {
		return this.iaaSSecurityGroupRules;
	}

	public void setIaaSSecurityGroupRules(
			Set<IaaSSecurityGroupRule> iaaSSecurityGroupRules) {
		this.iaaSSecurityGroupRules = iaaSSecurityGroupRules;
	}

}
