package it.prisma.monitoringpillar.db;

// Generated Aug 29, 2014 7:02:25 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PrismamonitoringServersId generated by hbm2java
 */
@Embeddable
public class PrismamonitoringServersId implements java.io.Serializable {

	private String zabbixServerName;
	private String testbedName;
	private String prismamonitoredHostNames;

	public PrismamonitoringServersId() {
	}

	public PrismamonitoringServersId(String zabbixServerName,
			String testbedName, String prismamonitoredHostNames) {
		this.zabbixServerName = zabbixServerName;
		this.testbedName = testbedName;
		this.prismamonitoredHostNames = prismamonitoredHostNames;
	}

	@Column(name = "ZabbixServerName", nullable = false, length = 45)
	public String getZabbixServerName() {
		return this.zabbixServerName;
	}

	public void setZabbixServerName(String zabbixServerName) {
		this.zabbixServerName = zabbixServerName;
	}

	@Column(name = "TestbedName", nullable = false, length = 45)
	public String getTestbedName() {
		return this.testbedName;
	}

	public void setTestbedName(String testbedName) {
		this.testbedName = testbedName;
	}

	@Column(name = "PRISMAMonitoredHostNames", nullable = false, length = 45)
	public String getPrismamonitoredHostNames() {
		return this.prismamonitoredHostNames;
	}

	public void setPrismamonitoredHostNames(String prismamonitoredHostNames) {
		this.prismamonitoredHostNames = prismamonitoredHostNames;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrismamonitoringServersId))
			return false;
		PrismamonitoringServersId castOther = (PrismamonitoringServersId) other;

		return ((this.getZabbixServerName() == castOther.getZabbixServerName()) || (this
				.getZabbixServerName() != null
				&& castOther.getZabbixServerName() != null && this
				.getZabbixServerName().equals(castOther.getZabbixServerName())))
				&& ((this.getTestbedName() == castOther.getTestbedName()) || (this
						.getTestbedName() != null
						&& castOther.getTestbedName() != null && this
						.getTestbedName().equals(castOther.getTestbedName())))
				&& ((this.getPrismamonitoredHostNames() == castOther
						.getPrismamonitoredHostNames()) || (this
						.getPrismamonitoredHostNames() != null
						&& castOther.getPrismamonitoredHostNames() != null && this
						.getPrismamonitoredHostNames().equals(
								castOther.getPrismamonitoredHostNames())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getZabbixServerName() == null ? 0 : this
						.getZabbixServerName().hashCode());
		result = 37
				* result
				+ (getTestbedName() == null ? 0 : this.getTestbedName()
						.hashCode());
		result = 37
				* result
				+ (getPrismamonitoredHostNames() == null ? 0 : this
						.getPrismamonitoredHostNames().hashCode());
		return result;
	}

}
