package it.prisma.monitoringpillar.db;

// Generated Aug 29, 2014 7:02:25 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PrismamonitoringServers generated by hbm2java
 */
@Entity
@Table(name = "PRISMAMonitoringServers", catalog = "monitoring")
public class PrismamonitoringServers implements java.io.Serializable {

	private PrismamonitoringServersId id;
	private PrismamonitoredHosts prismamonitoredHosts;

	public PrismamonitoringServers() {
	}

	public PrismamonitoringServers(PrismamonitoringServersId id,
			PrismamonitoredHosts prismamonitoredHosts) {
		this.id = id;
		this.prismamonitoredHosts = prismamonitoredHosts;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "zabbixServerName", column = @Column(name = "ZabbixServerName", nullable = false, length = 45)),
			@AttributeOverride(name = "testbedName", column = @Column(name = "TestbedName", nullable = false, length = 45)),
			@AttributeOverride(name = "prismamonitoredHostNames", column = @Column(name = "PRISMAMonitoredHostNames", nullable = false, length = 45)) })
	public PrismamonitoringServersId getId() {
		return this.id;
	}

	public void setId(PrismamonitoringServersId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRISMAMonitoredHostNames", nullable = false, insertable = false, updatable = false)
	public PrismamonitoredHosts getPrismamonitoredHosts() {
		return this.prismamonitoredHosts;
	}

	public void setPrismamonitoredHosts(
			PrismamonitoredHosts prismamonitoredHosts) {
		this.prismamonitoredHosts = prismamonitoredHosts;
	}

}
