// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package it.prisma.businesslayer.orchestrator.dsl;

public class CloudifyDeploymentDataBuilder extends
		CloudifyDeploymentDataBuilderBase<CloudifyDeploymentDataBuilder> {
	public static CloudifyDeploymentDataBuilder cloudifyDeploymentData() {
		return new CloudifyDeploymentDataBuilder();
	}

	public CloudifyDeploymentDataBuilder() {
		super(new CloudifyDeploymentData());
	}

	public CloudifyDeploymentData build() {
		return getInstance();
	}
}

class CloudifyDeploymentDataBuilderBase<GeneratorT extends CloudifyDeploymentDataBuilderBase<GeneratorT>> {
	private CloudifyDeploymentData instance;

	protected CloudifyDeploymentDataBuilderBase(CloudifyDeploymentData aInstance) {
		instance = aInstance;
	}

	protected CloudifyDeploymentData getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withRecipePropertiesFile(String aValue) {
		instance.setRecipePropertiesFile(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withApplicationName(String aValue) {
		instance.setApplicationName(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withApplicationDeploymentID(String aValue) {
		instance.setApplicationDeploymentID(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withRecipeName(String aValue) {
		instance.setRecipeName(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withRecipeVersion(String aValue) {
		instance.setRecipeVersion(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withRecipeURL(String aValue) {
		instance.setRecipeURL(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withCustomizedRecipePath(String aValue) {
		instance.setCustomizedRecipePath(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withRecipeUploadKey(String aValue) {
		instance.setRecipeUploadKey(aValue);

		return (GeneratorT) this;
	}
}
