// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package it.prisma.businesslayer.orchestrator.dsl;

import it.prisma.businesslayer.orchestrator.dsl.Credentials.CredentialsType;

public class CloudifyEndpointBuilder extends
		CloudifyEndpointBuilderBase<CloudifyEndpointBuilder> {
	public static CloudifyEndpointBuilder cloudifyEndpoint() {
		return new CloudifyEndpointBuilder();
	}

	public CloudifyEndpointBuilder() {
		super(new CloudifyEndpoint());
	}

	public CloudifyEndpoint build() {
		return getInstance();
	}
}

class CloudifyEndpointBuilderBase<GeneratorT extends CloudifyEndpointBuilderBase<GeneratorT>> {
	private CloudifyEndpoint instance;

	protected CloudifyEndpointBuilderBase(CloudifyEndpoint aInstance) {
		instance = aInstance;
	}

	protected CloudifyEndpoint getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withVersion(String aValue) {
		instance.setVersion(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withUrl(String aValue) {
		instance.setUrl(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withCredentials(Credentials aValue) {
		instance.setCredentials(aValue);

		return (GeneratorT) this;
	}

	public CredentialsCredentialsBuilder withCredentials() {
		Credentials obj = new Credentials();

		withCredentials(obj);

		return new CredentialsCredentialsBuilder(obj);
	}

	public class CredentialsCredentialsBuilder extends
			CredentialsBuilderBase<CredentialsCredentialsBuilder> {
		public CredentialsCredentialsBuilder(Credentials aInstance) {
			super(aInstance);
		}

		@SuppressWarnings("unchecked")
		public GeneratorT endCredentials() {
			return (GeneratorT) CloudifyEndpointBuilderBase.this;
		}
	}

	public static class CredentialsBuilderBase<GeneratorT extends CredentialsBuilderBase<GeneratorT>> {
		private Credentials instance;

		protected CredentialsBuilderBase(Credentials aInstance) {
			instance = aInstance;
		}

		protected Credentials getInstance() {
			return instance;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withType(CredentialsType aValue) {
			instance.setType(aValue);

			return (GeneratorT) this;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withUsername(String aValue) {
			instance.setUsername(aValue);

			return (GeneratorT) this;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withPassword(String aValue) {
			instance.setPassword(aValue);

			return (GeneratorT) this;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withToken(String aValue) {
			instance.setToken(aValue);

			return (GeneratorT) this;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withCustomCredentialsData(Object aValue) {
			instance.setCustomCredentialsData(aValue);

			return (GeneratorT) this;
		}
	}
}
