// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package it.prisma.businesslayer.orchestrator.dsl;

import it.prisma.businesslayer.orchestrator.dsl.Credentials.CredentialsType;

public class CredentialsBuilder extends
		CredentialsBuilderBase<CredentialsBuilder> {
	public static CredentialsBuilder credentials() {
		return new CredentialsBuilder();
	}

	public CredentialsBuilder() {
		super(new Credentials());
	}

	public Credentials build() {
		return getInstance();
	}
}

class CredentialsBuilderBase<GeneratorT extends CredentialsBuilderBase<GeneratorT>> {
	private Credentials instance;

	protected CredentialsBuilderBase(Credentials aInstance) {
		instance = aInstance;
	}

	protected Credentials getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withType(CredentialsType aValue) {
		instance.setType(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withUsername(String aValue) {
		instance.setUsername(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withPassword(String aValue) {
		instance.setPassword(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withToken(String aValue) {
		instance.setToken(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withCustomCredentialsData(Object aValue) {
		instance.setCustomCredentialsData(aValue);

		return (GeneratorT) this;
	}
}
