// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package it.prisma.businesslayer.orchestrator.dsl;

import it.prisma.businesslayer.orchestrator.dsl.deployment.DeployerType;
import it.prisma.dal.entities.accounting.UserAccount;
import it.prisma.dal.entities.accounting.Workgroup;
import it.prisma.dal.entities.paas.deployments.PaaSDeployment;
import it.prisma.dal.entities.paas.services.AbstractPaaSService;
import it.prisma.domain.dsl.paas.services.generic.request.GenericPaaSServiceDeployRequest;

public class DeploymentMessageBuilder extends
		DeploymentMessageBuilderBase<DeploymentMessageBuilder> {
	public static DeploymentMessageBuilder deploymentMessage() {
		return new DeploymentMessageBuilder();
	}

	public DeploymentMessageBuilder() {
		super(new DeploymentMessage());
	}

	public DeploymentMessage build() {
		return getInstance();
	}
}

class DeploymentMessageBuilderBase<GeneratorT extends DeploymentMessageBuilderBase<GeneratorT>> {
	private DeploymentMessage instance;

	protected DeploymentMessageBuilderBase(DeploymentMessage aInstance) {
		instance = aInstance;
	}

	protected DeploymentMessage getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withDeployRequest(GenericPaaSServiceDeployRequest aValue) {
		instance.setDeployRequest(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withDeployerType(DeployerType aValue) {
		instance.setDeployerType(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withInfrastructureData(InfrastructureData aValue) {
		instance.setInfrastructureData(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withPaaSService(AbstractPaaSService aValue) {
		instance.setPaaSService(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withPaasDeployment(PaaSDeployment aValue) {
		instance.setPaasDeployment(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withUserAccount(UserAccount aValue) {
		instance.setUserAccount(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withWorkgroup(Workgroup aValue) {
		instance.setWorkgroup(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withDeploymentData(DeployerDeploymentData aValue) {
		instance.setDeploymentData(aValue);

		return (GeneratorT) this;
	}
}
