// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package it.prisma.businesslayer.orchestrator.dsl;

public class HeatDeploymentDataBuilder extends
		HeatDeploymentDataBuilderBase<HeatDeploymentDataBuilder> {
	public static HeatDeploymentDataBuilder heatDeploymentData() {
		return new HeatDeploymentDataBuilder();
	}

	public HeatDeploymentDataBuilder() {
		super(new HeatDeploymentData());
	}

	public HeatDeploymentData build() {
		return getInstance();
	}
}

class HeatDeploymentDataBuilderBase<GeneratorT extends HeatDeploymentDataBuilderBase<GeneratorT>> {
	private HeatDeploymentData instance;

	protected HeatDeploymentDataBuilderBase(HeatDeploymentData aInstance) {
		instance = aInstance;
	}

	protected HeatDeploymentData getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withTemplateName(String aValue) {
		instance.setTemplateName(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withTemplateVersion(String aValue) {
		instance.setTemplateVersion(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withTemplateURL(String aValue) {
		instance.setTemplateURL(aValue);

		return (GeneratorT) this;
	}
}
