// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package it.prisma.businesslayer.orchestrator.dsl;

import it.prisma.businesslayer.orchestrator.dsl.deployment.DeployerType;
import it.prisma.dal.entities.iaas.tenant.IaaSTenant;

public class InfrastructureDataBuilder extends
		InfrastructureDataBuilderBase<InfrastructureDataBuilder> {
	public static InfrastructureDataBuilder infrastructureData() {
		return new InfrastructureDataBuilder();
	}

	public InfrastructureDataBuilder() {
		super(new InfrastructureData());
	}

	public InfrastructureData build() {
		return getInstance();
	}
}

class InfrastructureDataBuilderBase<GeneratorT extends InfrastructureDataBuilderBase<GeneratorT>> {
	private InfrastructureData instance;

	protected InfrastructureDataBuilderBase(InfrastructureData aInstance) {
		instance = aInstance;
	}

	protected InfrastructureData getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withZone(PrismaZone aValue) {
		instance.setZone(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withType(DeployerType aValue) {
		instance.setType(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withIaasTenant(IaaSTenant aValue) {
		instance.setIaasTenant(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withMonitoringEndpoint(MonitoringEndpoint aValue) {
		instance.setMonitoringEndpoint(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withMailEndpoint(MailEndpoint aValue) {
		instance.setMailEndpoint(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withDeployerEndpoint(DeployerEndpoint aValue) {
		instance.setDeployerEndpoint(aValue);

		return (GeneratorT) this;
	}
}
