// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package it.prisma.businesslayer.orchestrator.dsl;

public class PrismaZoneBuilder extends PrismaZoneBuilderBase<PrismaZoneBuilder> {
	public static PrismaZoneBuilder prismaZone() {
		return new PrismaZoneBuilder();
	}

	public PrismaZoneBuilder() {
		super(new PrismaZone());
	}

	public PrismaZone build() {
		return getInstance();
	}
}

class PrismaZoneBuilderBase<GeneratorT extends PrismaZoneBuilderBase<GeneratorT>> {
	private PrismaZone instance;

	protected PrismaZoneBuilderBase(PrismaZone aInstance) {
		instance = aInstance;
	}

	protected PrismaZone getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withName(String aValue) {
		instance.setName(aValue);

		return (GeneratorT) this;
	}
}
