// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package it.prisma.businesslayer.orchestrator.dsl;

public class QuotaLimitsBuilder extends
		QuotaLimitsBuilderBase<QuotaLimitsBuilder> {
	public static QuotaLimitsBuilder quotaLimits() {
		return new QuotaLimitsBuilder();
	}

	public QuotaLimitsBuilder() {
		super(new QuotaLimits());
	}

	public QuotaLimits build() {
		return getInstance();
	}
}

class QuotaLimitsBuilderBase<GeneratorT extends QuotaLimitsBuilderBase<GeneratorT>> {
	private QuotaLimits instance;

	protected QuotaLimitsBuilderBase(QuotaLimits aInstance) {
		instance = aInstance;
	}

	protected QuotaLimits getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withCpus(int aValue) {
		instance.setCpus(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withRam(int aValue) {
		instance.setRam(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withInstances(int aValue) {
		instance.setInstances(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withVolumes(int aValue) {
		instance.setVolumes(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withVolumeSize(int aValue) {
		instance.setVolumeSize(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withIps(int aValue) {
		instance.setIps(aValue);

		return (GeneratorT) this;
	}
}
