package it.prisma.dal.entities.paas.services.caaas;

//Generated Sep 8, 2014 12:47:13 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Configurations generated by hbm2java
 */
@Entity
@Table(name = "ejbcaCost")
public class EjbcaCost implements java.io.Serializable {

	private static final long serialVersionUID = 5118051185605529700L;

	private long id;
	private String username;
	private String certificateSN;
	private String date;
	private int cost;

	public EjbcaCost() {
	}

	public EjbcaCost(String username, String certificateSN, String date,
			int cost) {
		super();
		this.username = username;
		this.certificateSN = certificateSN;
		this.date = date;
		this.cost = cost;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "username")
	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "certificateSN")
	public String getCertificateSN() {
		return certificateSN;
	}

	public void setCertificateSN(String certificateSN) {
		this.certificateSN = certificateSN;
	}

	@Column(name = "date")
	public String getDate() {
		return date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Column(name = "cost")
	public int getCost() {
		return cost;
	}

	public void setCost(int cost) {
		this.cost = cost;
	}

}
