package it.prisma.dal.entities.orchestrator.lrt;

// Generated 17-set-2014 21.25.53 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import org.hibernate.annotations.Type;

/**
 * Lrtevent generated by hbm2java
 */
@Entity
@Table(name = "LRTEvent")
public class LRTEvent implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4610359126709352740L;

	public enum LRTEventType {
		INFO, ERROR, WARN, RESULT
	}
	
	private Long eventId;
	private Date createdAt;
	private LRT lrt;
	private String data;
	private LRTEventType eventType;

	public LRTEvent() {
	}

	public LRTEvent(LRT lrt, LRTEventType eventType, String data) {
		this.lrt = lrt;
		this.data = data;
		this.eventType = eventType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "EventID", unique = true, nullable = false)
	public Long getId() {
		return this.eventId;
	}

	public void setId(Long eventId) {
		this.eventId = eventId;
	}

	@Version
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdAt", nullable = false, length = 19, insertable=false, updatable=false)
	public Date getTimestamp() {
		return this.createdAt;
	}

	public void setTimestamp(Date createdAt) {
		this.createdAt = createdAt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LRTID", nullable = false)
	public LRT getLrt() {
		return this.lrt;
	}

	public void setLrt(LRT lrt) {
		this.lrt = lrt;
	}

	@Column(name = "data", nullable = false, length=65535)
	@Type(type="text")
	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

	@Column(name = "eventType", nullable = false)
	public LRTEventType getEventType() {
		return this.eventType;
	}

	public void setEventType(LRTEventType eventType) {
		this.eventType = eventType;
	}
}
