package it.prisma.dal.entities.paas.services.emailaas;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Configurations generated by hbm2java
 */
@Entity
@Table(name = "virtual_domains") 
public class VirtualDomains implements java.io.Serializable {

	private static final long serialVersionUID = 3236127571453501063L;
	private Long id;
	private String name;

	public VirtualDomains() {
	}

	public VirtualDomains(String name) {
		super();	
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
}
